# Generated by Django 2.0.7 on 2018-07-31 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cname', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Up to 15 digits allowed.", regex='^\\d{9,10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Med_Client_mapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price_per_box', models.DecimalField(decimal_places=3, max_digits=10)),
                ('no_of_box_sell', models.DecimalField(decimal_places=3, max_digits=10)),
                ('client_contact_mapper', models.ForeignKey(on_delete='models.CASCADE', related_name='mapper', to='medicines.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('mname', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('med_type', models.CharField(max_length=50)),
                ('company_cost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lending_cost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('opening_unit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('recieving_unit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('closing_unit', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='med_client_mapper',
            name='mname_mapper',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='mapper', to='medicines.Medicines'),
        ),
    ]
