# Generated by Django 2.0.7 on 2018-07-31 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cname',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=11, primary_key=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '999999999'. Up to 15 digits allowed.", regex='^\\d{9,10}$')]),
        ),
        migrations.AlterField(
            model_name='med_client_mapper',
            name='client_contact_mapper',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='Client', to='medicines.Client'),
        ),
        migrations.AlterField(
            model_name='med_client_mapper',
            name='mname_mapper',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='Medicines', to='medicines.Medicines'),
        ),
    ]
