# Generated by Django 2.1 on 2018-08-18 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_auto_20180818_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='med_transaction',
            name='date_of_transaction',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
